version: '3.7'
services:
  frontend:
    container_name: frontend-react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000